/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ProfileImport } from './routes/profile'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as AboutRoute1Import } from './routes/about.route1'

// Create/Update Routes

const ProfileRoute = ProfileImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute1Route = AboutRoute1Import.update({
  id: '/route1',
  path: '/route1',
  getParentRoute: () => AboutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileImport
      parentRoute: typeof rootRoute
    }
    '/about/route1': {
      id: '/about/route1'
      path: '/route1'
      fullPath: '/about/route1'
      preLoaderRoute: typeof AboutRoute1Import
      parentRoute: typeof AboutImport
    }
  }
}

// Create and export the route tree

interface AboutRouteChildren {
  AboutRoute1Route: typeof AboutRoute1Route
}

const AboutRouteChildren: AboutRouteChildren = {
  AboutRoute1Route: AboutRoute1Route,
}

const AboutRouteWithChildren = AboutRoute._addFileChildren(AboutRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/profile': typeof ProfileRoute
  '/about/route1': typeof AboutRoute1Route
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/profile': typeof ProfileRoute
  '/about/route1': typeof AboutRoute1Route
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/profile': typeof ProfileRoute
  '/about/route1': typeof AboutRoute1Route
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/profile' | '/about/route1'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/profile' | '/about/route1'
  id: '__root__' | '/' | '/about' | '/profile' | '/about/route1'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRouteWithChildren
  ProfileRoute: typeof ProfileRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRouteWithChildren,
  ProfileRoute: ProfileRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/profile"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx",
      "children": [
        "/about/route1"
      ]
    },
    "/profile": {
      "filePath": "profile.tsx"
    },
    "/about/route1": {
      "filePath": "about.route1.tsx",
      "parent": "/about"
    }
  }
}
ROUTE_MANIFEST_END */
